### ISSUE TITLE
Tohle by mely byt atributy tridy GamePlay

### ISSUE THREAD

**Issue by MrPateyl** [Eitheriel/some_games#1]
Hoj!

https://github.com/Eitheriel/some_games/blob/1b1fc4b974b44bf7c8414bfc3be63c65a97cc0e9/pexeso.py#L188-L189

Tohle by mely byt atributy tridy GamePlay - nemusis je pak pokazde predavat v parametrech, ale muzes se na ne odvolavat pomoci self.win a self.win_count.

**Comment by Eitheriel** [comment]
To je skvělý tip, díky! :-)

**Comment by MrPateyl** [comment]
Hoj!

Tahle varianta je sice mozna, ale v zasade zbytecne ukecana :)

https://github.com/Eitheriel/some_games/blob/743697d8fda7b0e0533663d8bdf8f8eb2fd1831b/pexeso.py#L197

Je vysoce nepravdepodobne, ze bys tridu GamePlay inicializovat s jinymi parametry nez ["", 0,0], 0 - proto bych si klidne dovolil vynechat ty parametry metody __init__ a ty atributy iniciovat natvrdo uvnitr te metody.

Kdybys ale opravdy chtel, nekdy GamePlay inicializovat i necim jinym, tak by tomu rozhodne sluselo, aby ty parametry mely defaultni hodnotu a pokud zrovna opravdu nechces ty parametry nastavovat jinak, tak aby stacilo volat jenom game = GamePlay().

**Comment by Eitheriel** [comment]
Ahoj,
díky za kontrolu :-) Zapomněl jsem tam nahrát novou verzi, postupně to upravuju ještě :-)
 
Mám dva dotazy na Tvé poznámky:
1) Dost mozna, ze bych ani nevytvarel motodu "board_Stuffing" ale jeji kod napsal primo do **init** - nikde jinde to stejne nevolas.
Dotaz: Do init  se dát celý kód? Všude jsem viděl jen nějaké ty atributy, ale ne celou "metodu"
 
2) jo - a samozrejme i "stuff" bych dal jako atribut objektu battle ;)
Dotaz: Jako atribut to můžu dát, ale používám to i v instanci game... ono se todá nějak udělat, aby atribut jedné instance byl k dispozici jiné instance?
 
Díky,
Vašek
 
______________________________________________________________
> Od: "MrPateyl" <notifications@github.com>
> Komu: "Eitheriel/some_games" <some_games@noreply.github.com>
> Datum: 09.02.2019 23:56
> Předmět: Re: [Eitheriel/some_games] Tohle by mely byt atributy tridy GamePlay (#1)
>
Hoj!
Tahle varianta je sice mozna, ale v zasade zbytecne ukecana :)
https://github.com/Eitheriel/some_games/blob/743697d8fda7b0e0533663d8bdf8f8eb2fd1831b/pexeso.py#L197 <https://github.com/Eitheriel/some_games/blob/743697d8fda7b0e0533663d8bdf8f8eb2fd1831b/pexeso.py#L197>
Je vysoce nepravdepodobne, ze bys tridu GamePlay inicializovat s jinymi parametry nez ["", 0,0], 0 - proto bych si klidne dovolil vynechat ty parametry metody init a ty atributy iniciovat natvrdo uvnitr te metody.
Kdybys ale opravdy chtel, nekdy GamePlay inicializovat i necim jinym, tak by tomu rozhodne sluselo, aby ty parametry mely defaultni hodnotu a pokud zrovna opravdu nechces ty parametry nastavovat jinak, tak aby stacilo volat jenom game = GamePlay().

**Comment by Eitheriel** [comment]
Už je tam nová verze.. :-)
 
______________________________________________________________
> Od: "MrPateyl" <notifications@github.com>
> Komu: "Eitheriel/some_games" <some_games@noreply.github.com>
> Datum: 09.02.2019 23:56
> Předmět: Re: [Eitheriel/some_games] Tohle by mely byt atributy tridy GamePlay (#1)
>
Hoj!
Tahle varianta je sice mozna, ale v zasade zbytecne ukecana :)
https://github.com/Eitheriel/some_games/blob/743697d8fda7b0e0533663d8bdf8f8eb2fd1831b/pexeso.py#L197 <https://github.com/Eitheriel/some_games/blob/743697d8fda7b0e0533663d8bdf8f8eb2fd1831b/pexeso.py#L197>
Je vysoce nepravdepodobne, ze bys tridu GamePlay inicializovat s jinymi parametry nez ["", 0,0], 0 - proto bych si klidne dovolil vynechat ty parametry metody init a ty atributy iniciovat natvrdo uvnitr te metody.
Kdybys ale opravdy chtel, nekdy GamePlay inicializovat i necim jinym, tak by tomu rozhodne sluselo, aby ty parametry mely defaultni hodnotu a pokud zrovna opravdu nechces ty parametry nastavovat jinak, tak aby stacilo volat jenom game = GamePlay().

**Comment by Eitheriel** [comment]
Ahoj, zapomněl jsem tam nahrát novou verzi, kde už je to iniciováno uvnitř metody. Už by tu měla být :-)

**Comment by MrPateyl** [comment]
jasan.
