### ISSUE TITLE
s rekurzi setri

### ISSUE THREAD

**Issue by MrPateyl** [Eitheriel/some_games#3]
https://github.com/Eitheriel/some_games/blob/1b1fc4b974b44bf7c8414bfc3be63c65a97cc0e9/pexeso.py#L175

Tohle Te usvedcuje z nedostatecneho beta-testovani - zrejme jsi to nikdy nezkousel dohrat  na maximalni velikost ....

... zhruba po 1000 kolech Ti to totiz spadne na prekroceni maximalni hloubky rekurze.

Je to proto, ze volani funkci (a tedy rekurze zejmena) je pomerne draha operace, pri ktere si pocitac musi pamatovat, kde presne skoncil s vykonavanim kodu pred volanim funkce a kde ma pak nasledne pokracovat pote, co tu funkci vykona. Vice viz https://en.wikipedia.org/wiki/Stack_overflow .

Rekurze je sice mocna zbran, ale tohle je ukazkovy pripad toho, kdy by misto rekurze mel byt pouzity cyklus.

**Comment by Eitheriel** [comment]
Aha, na to jsem vůbec nepomyslel. Hloupá chyba. Díky za tip.

**Comment by MrPateyl** [comment]
jasan
