### ISSUE TITLE
V obou polo-kolech Ti to pise, ze se jedna o prvni tah

### ISSUE THREAD

**Issue by MrPateyl** [Eitheriel/some_games#4]
https://github.com/Eitheriel/some_games/blob/1b1fc4b974b44bf7c8414bfc3be63c65a97cc0e9/pexeso.py#L138

**Comment by Eitheriel** [comment]
To jsem přehlédl, díky :-)

**Comment by MrPateyl** [comment]
ok - uz to funguje:)
