### ISSUE TITLE
Cislo hrace

### ISSUE THREAD

**Issue by MrPateyl** [Eitheriel/some_games#5]
https://github.com/Eitheriel/some_games/blob/1b1fc4b974b44bf7c8414bfc3be63c65a97cc0e9/pexeso.py#L144

Cislo hrace je dalsi z veci, kterou bych asi spis ukladal v atributu, at to porad nemusis predavat parametrem. Tak, jak to mas napsane, tak vubec nevyuzivas vyhod objektoveho programovani - formalne jsi sice ze vsech funkci udelal metody, ale de facto se jedna o "staticke funkce", ktere veskere vstupy dostavaji skrze parametry a nijak nepracuji s instancemi prislusnych trid (ani nectou stav, ani ho nemeni).

Navic je zde hrozne matouci, ze zde pouzivas parametr "i" - pojmenovani "player_number" je mnohem lepsi :)

**Comment by MrPateyl** [comment]
Tak zde je to 50:50 - ted uz ty hodnoty mas ulozene v atributech objektu game, ale porad je predavas parametry - proc?

**Comment by Eitheriel** [comment]
No protože pro střídání 1. a 2. hráče ve hře stejně používám for cyklus, kde se střídá č. 1 a 2, tak proč to nevyužít i pro číslo hráče?

**Comment by MrPateyl** [comment]
jasan
