### ISSUE TITLE
opet atribut

### ISSUE THREAD

**Issue by MrPateyl** [Eitheriel/some_games#6]
https://github.com/Eitheriel/some_games/blob/1b1fc4b974b44bf7c8414bfc3be63c65a97cc0e9/pexeso.py#L183

Opet nevyuzivas objekty, ktere sis vytvoril. Vysledek metody riddle bych neukladal do globalni promenne riddle, ale ulozil si ho do atributu Gameplaye.

Navic bych metodu riddle volal uz z "konstruktoru" (metody __init__) tridy GamePlay, abys ji nemusel volat pokazde ruco.

```
class Gameplay:
    def __init__(self, x):
        self.riddle(x)
```

Potom staci hru vytvorit jen pomoci:
```game = Gameplay(x)```

**Comment by Eitheriel** [comment]
Upraveno :-)

**Comment by Eitheriel** [comment]
Co tu? Tady je to dobrý?

**Comment by MrPateyl** [comment]
jasan - ok.
