### ISSUE TITLE
Zase konstruktor

### ISSUE THREAD

**Issue by MrPateyl** [Eitheriel/some_games#7]
https://github.com/Eitheriel/some_games/blob/1b1fc4b974b44bf7c8414bfc3be63c65a97cc0e9/pexeso.py#L178

I tady bych "inicializacni kod" nacpal do metody __init__. Dost mozna, ze bych ani nevytvarel motodu "board_Stuffing" ale jeji kod napsal primo do __init__ - nikde jinde to stejne nevolas.

A jeste drobnostka ke nekonzistenci pojmenovani - board_Stuffing mas s velkym "S" zatimco co adjust_line s malym "L" - vypada to divne.

**Comment by MrPateyl** [comment]
jo - a samozrejme i "stuff" bych dal jako atribut objektu battle ;)

**Comment by Eitheriel** [comment]
Nikde jsem zatím neviděl, že by se celá metoda dala nacpat do konstruktoru. Poradíš, kde si o tom můžu přečíst víc? Zatím jsem to nikde nenašel...

"stuff" používám v instanci game... proto ji mám jako globální proměnnou. Leda by snad bylo možné atribut jedné třídy použít pro jinou třídu? :-O

**Comment by Eitheriel** [comment]
Koukal jsem, že se dá použít atribut z jedné instance v jiné instanci... mám to všechno předělat? Stuff, x, y,..?

**Comment by MrPateyl** [comment]
Toz mozna nerozumim otazace (nebo spis ani jedne)...

... metoda __init__ je metoda jako jakakoliv jina - muzes tam napsat volani vpodstate cehokoliv chces.

... no - a prave proto, ze "stuff" pouzivas v instanci (a navic dokonce nikde jinde), tak by to mel byt "instancni atribut".

.... a staticke atributy (atributy tridy) sem ani neplet :) ....
.... a ano atributy trid i instanci lze pouzivat i v jinych tridach / instancich - musis jen napsat cele jejich jmeno :)

**Comment by Eitheriel** [comment]
Tak už by mělo všechno být v konstruktorech. Abych zachoval univerzálnost třídy Battlefield i pro další programy, informace potřebné pro vytvoření hracího pole bylo nutné vložit jako argumenty každé instance.

**Comment by MrPateyl** [comment]
... skoro...

... zrejme jsme tu kazdy mluvili o jinem konstruktoru :) ...

.... na prvni pohled mne nenapad nic proti upravam Battlefield.__init__ ...

... ale co s tim battlem?:

https://github.com/Eitheriel/some_games/blob/c47ffe3c33d073fc66f0b75c003fa8624c3a9270/pexeso.py#L209

je to zbytecna globalni promenna - to by imo melo byt parametrem Gameplay.__init__

**Comment by MrPateyl** [comment]
... i kdyz podle vseho za to muzu ja - vypada to, ze jsem smichal dohromady narazky na oba konstruktory v jednom odstavci.

**Comment by Eitheriel** [comment]
V pohodě, mrknu na to zítra. Dneska už jsem nějak grogy :-) Moc Ti děkuji za pomoc!! :-)

**Comment by Eitheriel** [comment]
Už je to dobře? :-)

**Comment by MrPateyl** [comment]
Uf - to je zase zmen :) Popravde dnes jsem to vsechno nezvladl projit - ocividne tam doslo ke spouste zmen - nejen presun iniciacniho kodu - budu se na to muset podivat jindy.

Na prvni pohled je to na dobre ceste - libi se mi, ze parametry pro Battlefield si ted resi "konstruktor" Gameplaye - ale zarazilo mne, ze mas porad ten Battlefield ulozeny v globalni promenne battle - co Ti brani v tom z toho battle udelat atribut tridy Gameplay? (Tyka se to jak TicTacu tak Pexesa)

Dalsi detail, ktereho jsem si vsiml je umisteni atributu pro dimenze x, y i do attributu tridy Gameplay - proc myslis, ze to tam patri? IMO to jsou rozmery Battlefieldu - nikoliv Gameplaye.

Coz mne vede mozna k nejdulezitejsimu doporuceni dnesni varky - snaz se do jednotlivych commitu zahrnovat pouze zmeny, ktere maji za cil prave a jen nejakou konkretni zmenu (treba pridani hrace). Do popisu commitu je pak dobre popsat, co za zmenu bylo tou upravou sledovano - pomuze to pri cteni :).

Keep calm and carry on!
M.

PS - a samozrejme #8 DRY - diky tomu, ze mas Battlefield stale rozkopirovany, tak zbytecne delas stejne zmeny dvakrat na dvou mistech.

**Comment by Eitheriel** [comment]
Z globální proměnné "battle" jsem udělal atribut třídy Gameplay (u obou programů).

Co se týče x a y, to máš asi pravdu. To by tam měl patřit i "stuff", ne? Ale třeba v případě pexeso.py nepotřebuju po uživateli definovat dimenzi "y" (kartičky pexesa jsou rozložené do tvaru čtverce), takže takhle mi to přijde lepší. 

Ok, pokusím se ty commity víc rozepisovat :-D zatím ty změny jsou tak markantní, že bych vždycky popsal celý stoh :-)

**Comment by MrPateyl** [comment]
Parada - blizime se do finale :) - zbavili jsme se globalnich promennych a veskery inicializacni kod je schovany v konstruktorech.

Ci spise jednom konstruktoru - coz je docela podezrele...
... ale o tom zas nekdy jindy.

Abych to moc nenatahoval - a neresil vsechno v ramci jedne issue, tak tuhle jiz uzavru a na dalsi upravy zalozim nove.

Jinac to rozdeleni "problemu" do jednotlivych "issues" nedelam uplne samoucelne - vlastne se Ti tim snazim napovedet, jak mohou vypadat ty "konkretni" zmeny, ktere by vicemene mohly odpovidat jednotlivym commitum.

V ramci treninku jsou ty issues sice vpodstate banalni, ale ani v realu nejsou vyjimkou commity, kde zmenis i jen jeden znak - i kdyz to uz typicky byva oprava preklepu - nikoliv nova funkcionalita.

Do popisku commitu - pokud nejsi moc vyrecny - pak muze stacit napsat jen krizek a cislo issue - napr #7 - a github pak z toho "cisla" udela link na dany problem, ktery ten commit resi.

Vem to jako dalsi cviceni - zamer se na to, at v jednom commitu neresis vice zmen naraz. Sam s tim mam problemy, ale stoji to za to. Je to dulezity zvyk do budoucna, kdy budes resit slozitejsi upravy. 

Casto bys pak narazel na to, ze cast uprav, ktere provedes, si nakonec rozmyslis, ale pritom jine upravy bys chtel zachovat. Popkud bys vse mel v jednom commitu, tak to budes muset delat rucne. Pokud budes mit zmeny izolovane v ruznych commitech, tak budes moci nechtene zmeny zrusit typicky jedinnym prikazem (napriklad git revert).

Navic se to pak samozrejme lepe cte - a dobre citelny kod (a jeho zmeny) jsou nutnosti pro vetsi projekty - obzvlast, pokud na nich ma pracovat vic lidi.
